### ISSUE TITLE
Destroying sub-interfaces doesn't remove them from FMC

### ISSUE THREAD

**Issue by tiagosil-cisco** [CiscoDevNet/terraform-provider-fmc#140] opened 2023-11-02 01:00 UTC
When we destroy a sub-interface resource (fmc_device_subinterfaces) it doesn't remove it from the device

**Comment by snetlamu** [comment] 2023-11-07 04:34
Hi @tiagosil-cisco , we reproduced this scenario. It looks like a bug in the FMC UI and not in the provider. After destroy, going back to the device management page and navigating back to the device interfaces refreshes FMC UI to display the updated state.

**Comment by jeroenwittock** [comment] 2023-11-07 08:39
Let us know if you need further assistance with this, closing for now.

**Closed by jeroenwittock** 2023-11-07 08:39 UTC
